Remove transports field from js/ts as it is not mapped on server side
passwordless-lib/fido2-net-lib pull request #453
Opened 2023-10-23 15:19 UTC by joegoldman2

`AuthenticatorAttestationRawResponse.ResponseData` on server side doesn't contain any `Transports` property.

2023-10-26 04:57 UTC, joegoldman2 commented
@abergs, @aseigler this PR is ready to be reviewed

2023-11-10 14:16 UTC, abergs approved these changes

2023-11-10 14:32 UTC, abergs requested changes
Actually - [when reading the spec](https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialdescriptor-transports), My opinion is that we should add transports to our server side raw class.

2023-11-10 19:28 UTC, joegoldman2 commented
@abergs I added the transports on server side and tested manually (in addition to updating the unit tests).

2023-11-17 15:55 UTC, abergs approved these changes
@joegoldman2 Thank you, I think this looks solid.

Would welcome any second opinions from @iamcarbon or @aseigler, but I'm approving this.

2023-12-16 06:11 UTC, joegoldman2 commented
@iamcarbon, @aseigler any thoughs please?

2023-12-18 16:41 UTC, aseigler commented
Code looks reasonable to me, not sure what is going on with those failed tests.  Is that new or an environment issue?

2023-12-18 16:45 UTC, joegoldman2 commented
> Code looks reasonable to me, not sure what is going on with those failed tests. Is that new or an environment issue?

The dotnet format step has failed with `Unable to locate dotnet CLI. Ensure that it is on the PATH.`. Are you able to re-run the failed job?

2023-12-22 11:52 UTC, abergs commented
I'm trying to re-run those checks to see if can get this in!

2023-12-22 14:25 UTC, merged